[package]
name = "linux-kernel-module"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[features]
usbnet = []

[dependencies]
bitflags = "1"
intrusive-collections = "0.9"

[build-dependencies]
bindgen = "0.54"
cc = "1.0"
shlex = "0.1"
